fh=open("c:\\ExcelR/PythonForDS\\writefileexample.txt","w")
fh.write("Welcome to file handling on python \n")
fh.write("This is Second line \n")
fh.write("Always close the file once the job is done. \n")
fh.close()